name: Setup
description: Sets up Gorilla Tag build enviroment

inputs:
  working-dir:
    description: "Working directory"
    required: true

runs:
  using: "composite"
  steps:
    # Download required libraries
  - name: Download Stripped Libs
    uses: robinraju/release-downloader@v1.7
    with:
      repository: "Gorilla-Tag-Modding-Group/BeatStripper"
      latest: true
      fileName: "Stripped.zip"
  - name: Extract Stripped Libs
    shell: pwsh
    run: Expand-Archive .\Stripped.zip ${{ inputs.working-dir }}\Libs
  - name: Download Unity
    shell: pwsh
    run: |
      curl https://unity.bepinex.dev/libraries/2019.3.15.zip --output Unity.zip
      Expand-Archive Unity.zip ${{ inputs.working-dir }}\Libs -F
  - name: Download BepInEx
    uses: robinraju/release-downloader@v1.7
    with:
      repository: "BepInEx/BepInEx"
      latest: true
      fileName: "*"
  - name: Extract BepInEx
    shell: pwsh
    run: |
      Expand-Archive BepInEx_x64*.zip Temp
      cp Temp\BepInEx\core\*.dll ${{ inputs.working-dir }}\Libs
      rm Temp -Recurse